#pragma once

#define HELLO_WORLD 0

#define USE_MOTORS 1
#define USE_ACTUATORS 1
#define USE_IMU 0

#define USE_SERIAL_MONITOR 0
#define PRINT_ROTATION 0

#define MANUAL_I2C 0

#define ACTUATOR_INIT_TO_END_TIME 8000
#define ACTUATOR_INIT_END_TO_MID_TIME 3750
#define INITIAL_DIRECTION 1

#define L_DRIVE_PWM_PIN D12
#define L_DRIVE_DIR_PIN D11

#define R_DRIVE_PWM_PIN D10
#define R_DRIVE_DIR_PIN D9

#define TL_LEG_PWM_PIN D8
#define TL_LEG_DIR_PIN D7

#define TR_LEG_PWM_PIN D4
#define TR_LEG_DIR_PIN D3

#define BL_LEG_PWM_PIN D6
#define BL_LEG_DIR_PIN D5

#define BR_LEG_PWM_PIN D1
#define BR_LEG_DIR_PIN D0